In [5]:
import pandas as pd
import numpy as np

## pre process
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

## models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

## metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

In [6]:
import os
os.chdir(r'C:\Users\AnuragS\OneDrive\cv_project\2 Stage Loan Approval & Validation System\data')
os.getcwd()

'C:\\Users\\AnuragS\\OneDrive\\cv_project\\2 Stage Loan Approval & Validation System\\data'

In [7]:
df = pd.read_csv('classification_data.csv')
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets,loan_income_ratio,asset_coverage_ratio,income_per_dependent,wealth_cibil_score,loan_status
0,2,1,0,9600000,29900000,12,778,50700000.0,3.114583,1.695652,3.200000e+06,3.944460e+10,1
1,0,0,1,4100000,12200000,8,417,17000000.0,2.975610,1.393443,4.100000e+06,7.089000e+09,0
2,3,1,0,9100000,29700000,20,506,57700000.0,3.263736,1.942761,2.275000e+06,2.919620e+10,0
3,3,1,0,8200000,30700000,8,467,52700000.0,3.743902,1.716612,2.050000e+06,2.461090e+10,0
4,5,0,1,9800000,24200000,20,382,55000000.0,2.469388,2.272727,1.633333e+06,2.101000e+10,0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   no_of_dependents      4269 non-null   int64
 1   education             4269 non-null   int64
 2   self_employed         4269 non-null   int64
 3   income_annum          4269 non-null   int64
 4   loan_amount           4269 non-null   int64
 5   loan_term             4269 non-null   int64
 6   cibil_score           4269 non-null   int64
 7   total_assets          4269 non-null   float64
 8   loan_income_ratio     4269 non-null   float64
 9   asset_coverage_ratio  4269 non-null   float64
 10  income_per_dependent  4269 non-null   float64
 11  wealth_cibil_score    4269 non-null   float64
 12  loan_status           4269 non-null   int64
dtypes: float64(5), int64(8)
memory usage: 433.7 KB

#### Define X & y

In [11]:
X = df.drop('loan_status',axis=1)
y = df['loan_status']

print(f'Shape of X: {X.shape}')
print(f'Shape of y: {y.shape}')

Shape of X: (4269, 12)
Shape of y: (4269,)

#### Train Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

print(X_train.shape)
print(X_test.shape)

(3415, 12)
(854, 12)

#### Logistic Regression

In [21]:
logistic_reg_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

logistic_reg_pipeline.fit(X_train, y_train)

y_pred_lr = logistic_reg_pipeline.predict(X_test)

y_prob_lr = logistic_reg_pipeline.predict_proba(X_test)[:,1]

print("LOGISTIC REGRESSION")

classification_report_lr = classification_report(y_test,y_pred_lr)
roc_auc_lr = roc_auc_score(y_test,y_pred_lr)
accuracy_lr = accuracy_score(y_test,y_pred_lr)
precision_lr = precision_score(y_test,y_pred_lr)
recall_lr = recall_score(y_test,y_pred_lr)
f1_lr = f1_score(y_test,y_pred_lr)

print(classification_report_lr)

print("ROC AUC:",roc_auc_lr)

LOGISTIC REGRESSION
              precision    recall  f1-score   support

           0       0.90      0.87      0.89       323
           1       0.92      0.94      0.93       531

    accuracy                           0.91       854
   macro avg       0.91      0.91      0.91       854
weighted avg       0.91      0.91      0.91       854

ROC AUC: 0.9057943129675302

#### Random Forest

In [22]:
rf = RandomForestClassifier()

rf.fit(X_train,y_train)

y_pred_rf = rf.predict(X_test)

y_prob_rf = rf.predict_proba(X_test)[:,1]

print("RANDOM FOREST")

classification_report_rf = classification_report(y_test,y_pred_rf)
roc_auc_rf = roc_auc_score(y_test,y_pred_rf)
accuracy_rf = accuracy_score(y_test,y_pred_rf)
precision_rf = precision_score(y_test,y_pred_rf)
recall_rf = recall_score(y_test,y_pred_rf)
f1_rf = f1_score(y_test,y_pred_rf)

print(classification_report_rf)

print("ROC AUC:",roc_auc_rf)

RANDOM FOREST
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       323
           1       1.00      1.00      1.00       531

    accuracy                           1.00       854
   macro avg       1.00      1.00      1.00       854
weighted avg       1.00      1.00      1.00       854

ROC AUC: 0.9969040247678019

#### XGBoost

In [23]:
xgb = XGBClassifier()

xgb.fit(X_train,y_train)

y_pred_xgb = xgb.predict(X_test)

xgb_prob = xgb.predict_proba(X_test)[:,1]

print("XGBOOST")

classification_report_xgb = classification_report(y_test,y_pred_xgb)
roc_auc_xgb = roc_auc_score(y_test,y_pred_xgb)
accuracy_xgb = accuracy_score(y_test,y_pred_xgb)
precision_xgb = precision_score(y_test,y_pred_xgb)
recall_xgb = recall_score(y_test,y_pred_xgb)
f1_xgb = f1_score(y_test,y_pred_xgb)

print(classification_report_xgb)

print("ROC AUC:",roc_auc_xgb)

XGBOOST
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       323
           1       1.00      1.00      1.00       531

    accuracy                           1.00       854
   macro avg       1.00      1.00      1.00       854
weighted avg       1.00      1.00      1.00       854

ROC AUC: 0.9959624051821145

#### Model Comparison

In [24]:
model_names = ['Logistic Regression','Random Forest','XGBoost']
accuracy_scores = [accuracy_lr,accuracy_rf,accuracy_xgb]
precision_scores = [precision_lr,precision_rf,precision_xgb]
recall_scores = [recall_lr,recall_rf,recall_xgb]
f1_scores = [f1_lr,f1_rf,f1_xgb]
roc_auc_scores = [roc_auc_lr,roc_auc_rf,roc_auc_xgb]


results = pd.DataFrame({
    'Model': model_names,
    'Accuracy': accuracy_scores,
    'Precision': precision_scores,
    'Recall':recall_scores,
    'F1':f1_scores,
    'ROC_AUC':roc_auc_scores
})

results.sort_values('ROC_AUC',ascending=False)

                 Model  Accuracy  Precision    Recall        F1   ROC_AUC
1        Random Forest  0.997658   0.996248  1.000000  0.998120  0.996904
2              XGBoost  0.996487   0.996241  0.998117  0.997178  0.995962
0  Logistic Regression  0.914520   0.922509  0.941620  0.931966  0.905794